name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: self-hosted-arch
    container:
      image: local/arch-builder
      volumes:
        - cargo-registry:/usr/local/cargo/registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # --- 1. COMPILE BINARIES ---
      - name: Build Linux Binaries
        run: cargo build --release --features gui

      - name: Build Windows Binaries (Cross-compile)
        run: cargo build --release --target x86_64-pc-windows-gnu --features gui

      # --- 2. CREATE PACKAGES ---
      
      # A. Debian Package (using Linux binaries)
      - name: Create Debian Package
        run: |
          cargo deb --no-build --features gui
          # Save .deb to root so it survives 'rm -rf target'
          mv target/debian/*.deb .

      # B. Generic Archives (Binary & Source)
      - name: Create Generic Linux and Windows Archives
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            RAW_VERSION="${{ github.ref_name }}"
            CLEAN_VERSION=$(echo "$RAW_VERSION" | sed 's/^v//')
          else
            RAW_VERSION="debug-${{ github.sha }}"
            CLEAN_VERSION="$RAW_VERSION"
          fi
          
          # --- 1. Source Tarball (For AUR) ---
          # Use git archive. This guarantees ONLY source code is included.
          # It ignores the .deb, target/, and any other generated files in the workspace.
          git archive --format=tar.gz --prefix="cfait-${CLEAN_VERSION}/" -o "cfait-source-${RAW_VERSION}.tar.gz" HEAD
          
          # --- 2. Linux Binary Tarball (For users) ---
          mkdir "cfait-linux-${CLEAN_VERSION}"
          cp target/release/cfait "cfait-linux-${CLEAN_VERSION}/"
          cp target/release/gui "cfait-linux-${CLEAN_VERSION}/cfait-gui"
          cp README.md LICENSE "cfait-linux-${CLEAN_VERSION}/"
          cp assets/cfait.desktop "cfait-linux-${CLEAN_VERSION}/"
          cp assets/cfait.svg "cfait-linux-${CLEAN_VERSION}/"
          tar -czvf "cfait-linux-${RAW_VERSION}.tar.gz" "cfait-linux-${CLEAN_VERSION}"
          
          # --- 3. Windows Binary Zip ---
          mkdir -p windows-staging
          cp target/x86_64-pc-windows-gnu/release/cfait.exe windows-staging/
          cp target/x86_64-pc-windows-gnu/release/gui.exe windows-staging/cfait-gui.exe
          cp README.md LICENSE windows-staging/
          (cd windows-staging && zip -r "../cfait-windows-$RAW_VERSION.zip" .)

      # --- 3. VERIFY ARCH BUILD ---
      - name: Build Arch Linux Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          RAW_VERSION="${{ github.ref_name }}"
          CLEAN_VER=$(echo "$RAW_VERSION" | sed 's/^v//')
          
          # Hash the SOURCE tarball for the AUR PKGBUILD
          HASH=$(sha256sum "cfait-source-${RAW_VERSION}.tar.gz" | awk '{print $1}')
          
          # Update PKGBUILD (this modifies the file in ./packaging/arch/PKGBUILD)
          sed -i "s/pkgver=.*/pkgver=${CLEAN_VER}/" packaging/arch/PKGBUILD
          sed -i "s/'SKIP'/'$HASH'/" packaging/arch/PKGBUILD
          
          # Point PKGBUILD to the Release Asset we will upload
          NEW_SOURCE_URL="https://codeberg.org/trougnouf/cfait/releases/download/${RAW_VERSION}/cfait-source-${RAW_VERSION}.tar.gz"
          sed -i "s|source=.*|source=(\"cfait-source-${RAW_VERSION}.tar.gz::${NEW_SOURCE_URL}\")|" packaging/arch/PKGBUILD
          
          # Prepare the build directory
          mkdir -p arch-build
          cp packaging/arch/PKGBUILD arch-build/
          cp "cfait-source-${RAW_VERSION}.tar.gz" "arch-build/cfait-source-${RAW_VERSION}.tar.gz"

          # Instead of cleaning the build, we inject our pre-compiled artifacts
          # into the directory where `makepkg` will build the source.
          # `cargo` will detect that the binaries are already up-to-date and will not recompile.
          echo "Injecting pre-compiled binaries into makepkg's build environment..."
          BUILD_SRC_DIR="arch-build/src/cfait-${CLEAN_VER}"
          mkdir -p "${BUILD_SRC_DIR}"
          cp -r target "${BUILD_SRC_DIR}/"
          
          # Permission Fixes
          chown -R builder:builder arch-build
          chown -R builder:builder /usr/local/cargo
          
          # Build the package
          (
            cd arch-build
            su builder -c "makepkg --printsrcinfo > .SRCINFO"
            su builder -c "makepkg -f --noconfirm"
            cp PKGBUILD ../PKGBUILD-for-aur
            mv *.pkg.tar.zst ../
            mv .SRCINFO ../
          )
          
      # --- 4. UPLOAD ---
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git-cliff --config cliff.toml --verbose --latest --strip header --output CHANGELOG_RELEASE.md

      - name: Create Release and Upload
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          tea login add --name codeberg --url ${{ github.server_url }} --token ${{ secrets.RELEASE_TOKEN }}
          tea release delete --repo ${{ github.repository }} --confirm ${{ github.ref_name }} || true
          
          tea release create \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            --tag "${{ github.ref_name }}" \
            --note-file CHANGELOG_RELEASE.md

          # Define Files
          DEB_FILE=$(find . -maxdepth 1 -name "*.deb")
          ARCH_PKG_FILE=$(find . -maxdepth 1 -name "*.pkg.tar.zst" ! -name "*-debug-*")
          LINUX_BINARY=$(find . -maxdepth 1 -name "cfait-linux-*.tar.gz")
          SOURCE_TAR=$(find . -maxdepth 1 -name "cfait-source-*.tar.gz")
          WIN_ZIP=$(find . -maxdepth 1 -name "cfait-windows-*.zip")

          echo "Uploading..."
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$DEB_FILE"
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$LINUX_BINARY"
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$SOURCE_TAR"
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$WIN_ZIP"
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} "$ARCH_PKG_FILE"
          
          # Rename PKGBUILD back to standard name for the upload asset
          cp PKGBUILD-for-aur PKGBUILD
          tea release assets create --repo ${{ github.repository }} ${{ github.ref_name }} PKGBUILD

      - name: Publish to AUR
        if: startsWith(github.ref, 'refs/tags/')
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          mkdir -p /root/.ssh
          echo "$AUR_SSH_KEY" > /root/.ssh/aur_key
          chmod 600 /root/.ssh/aur_key
          ssh-keyscan aur.archlinux.org >> /root/.ssh/known_hosts
          export GIT_SSH_COMMAND="ssh -i /root/.ssh/aur_key -o UserKnownHostsFile=/root/.ssh/known_hosts"
          git config --global user.name "Cfait Bot (Benoit Brummer)"
          git config --global user.email "trougnouf@gmail.com"
          git clone ssh://aur@aur.archlinux.org/cfait.git aur-repo

          cp PKGBUILD-for-aur aur-repo/PKGBUILD
          cp .SRCINFO aur-repo/

          cd aur-repo
          git add PKGBUILD .SRCINFO
          
          if git diff --staged --quiet; then
            echo "No changes to AUR files."
          else
            git commit -m "Update to ${{ github.ref_name }}"
            git push
            echo "🚀 Successfully pushed to AUR!"
          fi