name: Test and Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: codeberg-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

      - name: Run linter (clippy)
        run: cargo clippy --all-features -- -D warnings

      - name: Run unit tests
        run: cargo test --all-features --verbose